services:
  - type: web
    name: vapi-unified-webhook
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VAPI_API_KEY
        sync: false
      - key: VAPI_ASSISTANT_ID
        sync: false
      - key: VAPI_PHONE_NUMBER_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
