services:
  - type: web
    name: vectorshift-ventures
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -l $PORT
    repo: https://github.com/vShift-Kid/vectorshiftventures.git
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
